name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nix-build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - 8107
          - 902
          - 924
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.5.3
        name: Checkout

      - uses: cachix/install-nix-action@v22
        name: Install Nix

      - uses: cachix/cachix-action@v12
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build --argstr compiler ghc${{ matrix.ghc }}
        name: Build Package

  stack-build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - 8.10.7
          - 9.0.2
          - 9.2.8

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Haskell
        uses: haskell/actions/setup@v2.4.3
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 2.11

      - name: Cache dependencies
        uses: actions/cache@v3.3.1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: stack build --system-ghc

      - name: Test
        run: stack test --system-ghc
        # Test fails with ld warnings on macos-stack combo
        continue-on-error: ${{ matrix.os == 'macos-latest' }}
